name: smartpaisaa
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  permission_handler: ^12.0.1
  get_it: ^7.6.4
  smswatcher: ^0.0.2
  sms_autofill: ^2.3.0
  shared_preferences: ^2.2.2
  flutter_sms_inbox: ^1.0.2
  package_info_plus: ^4.2.0
  fl_chart: ^0.66.0
  path: ^1.9.0
  intl: ^0.18.0
  http: ^1.1.0
  crypto: ^3.0.3
  sqflite: ^2.3.3 # Added from dependencies to avoid duplication
  flutter_local_notifications: ^17.2.2
  # File operations
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  device_info_plus: ^9.1.1
  local_auth: ^2.1.7
  #  file_picker: ^6.1.1
  url_launcher: ^6.2.4
  #  sms_advanced: ^1.0.1

  #  carousel_slider: ^4.2.1
  flutter_animate: ^4.2.0
  #  workmanager: ^0.4.1
  connectivity_plus: ^4.0.2
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^23.1.44
  uuid: ^4.1.0
  image: ^4.1.3
  encrypt: ^5.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    # ✅ LOTTIE ANIMATIONS
    - assets/animations/
    - assets/animations/loading_money.json
    #    - assets/animations/welcome_money.json
    - assets/animations/success_transaction.json
    - assets/animations/error.json
    #    - assets/animations/empty_state.json
    - assets/animations/sync_loading.json

    # ✅ IMAGES & ICONS
    - assets/images/app_icon.png
    - assets/icon/app_icon.png

    # ✅ DATA FILES
    - assets/data/
    - assets/data/default_categories.json
    - assets/data/bank_patterns.json
#flutter_launcher_icons:
#  android: true
#  ios: true
#  image_path: "assets/icon/app_icon.png"

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Regular.ttf
#        - asset: fonts/Roboto-Medium.ttf
#          weight: 500
#        - asset: fonts/Roboto-Bold.ttf
#          weight: 700
#
#    - family: Inter
#      fonts:
#        - asset: fonts/Inter-Regular.ttf
#        - asset: fonts/Inter-Medium.ttf
#          weight: 500
#        - asset: fonts/Inter-SemiBold.ttf
#          weight: 600
#        - asset: fonts/Inter-Bold.ttf
#          weight: 700
